import "./globals.css";
import Header from "./header";
import MySessionProvider from "./session-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="my-9 mx-3">
          <MySessionProvider>
            <Header></Header>
            {children}
          </MySessionProvider>
        </div>
      </body>
    </html>
  );
}
